version: "3"
services:
  postgres:
    restart: always
    image: postgres:latest # for production better to specify Postgres version
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user -h postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: test_pass
      POSTGRES_USER: test_user
      POSTGRES_DB: test_db

  main:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      interval: 2s
      retries: 100
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8080
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    links:
      - postgres
    #environment:
      #PORT: :8080
      #DB_PASS: test_pass
      #DN_USER: test_user
      #DB_NAME: test_db
      #DB_HOST: postgres